cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o cal.o cal.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ../common/math.o ../common/math.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ../common/string.o ../common/string.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ../common/strings.o ../common/strings.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ../common/stdio.o ../common/stdio.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ../common/stdlib.o ../common/stdlib.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/crt0.o lib/crt0.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/dirent.o lib/dirent.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/errno.o lib/errno.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/panic.o lib/panic.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/stdio.o lib/stdio.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/stdlib.o lib/stdlib.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/string.o lib/string.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/syscall.o lib/syscall.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/time.o lib/time.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o lib/unistd.o lib/unistd.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o cat.o cat.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o clear.o clear.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o cp.o cp.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o date.o date.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o echo.o echo.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o env.o env.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o fib.o fib.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o halt.o halt.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o imgview.o imgview.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o init.o init.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o getfb.o getfb.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o init-test.o init-test.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o kill.o kill.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ln.o ln.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ls.o ls.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o mandelbrot.o mandelbrot.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o mkdir.o mkdir.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o mouse-cursor.o mouse-cursor.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o mv.o mv.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o poweroff.o poweroff.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o ps.o ps.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o pwd.o pwd.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o reboot.o reboot.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o rm.o rm.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o rmdir.o rmdir.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o run-tests.o run-tests.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o sh.o sh.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o sleep.o sleep.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o touch.o touch.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o wc.o wc.c
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -MMD -MP -c -o xv6-usertests.o xv6-usertests.c
ar rcs libc.a ../common/math.o ../common/string.o ../common/strings.o ../common/stdio.o ../common/stdlib.o lib/crt0.o lib/dirent.o lib/errno.o lib/panic.o lib/stdio.o lib/stdlib.o lib/string.o lib/syscall.o lib/time.o lib/unistd.o

cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/cal cal.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/cat cat.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/clear clear.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/cp cp.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/date date.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/echo echo.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/env env.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/fib fib.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/halt halt.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/imgview imgview.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/init init.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/getfb getfb.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/init-test init-test.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/kill kill.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/ln ln.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/ls ls.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/mandelbrot mandelbrot.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/mkdir mkdir.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/mouse-cursor mouse-cursor.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/mv mv.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/poweroff poweroff.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/ps ps.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/pwd pwd.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/reboot reboot.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/rm rm.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/rmdir rmdir.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/run-tests run-tests.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/sh sh.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/sleep sleep.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/touch touch.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/wc wc.o -lc
cc -std=c11 -m32 -static -nostdlib -ffreestanding -U_FORTIFY_SOURCE -Wall -Wextra -pedantic -O2 -g -isystemlib -isystem.. -isystem../common -isystem../kernel/api -L. -o ../base/bin/xv6-usertests xv6-usertests.o -lc